require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'BugsnagErrorReport' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  
  use_frameworks!
  pod "LogglyLogger-CocoaLumberjack", "~> 2.0"

  target 'BugsnagErrorReportTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!
#  post_install do |installer|
#    flipper_post_install(installer)
#  end
end

target 'BugsnagErrorReport-tvOS' do
  # Pods for BugsnagErrorReport-tvOS

  target 'BugsnagErrorReport-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
